//
//  UIColor+Palette.h
//
//  Generated by Zeplin on 7/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (Palette)

+ (UIColor * _Nonnull)omg_ctaOpacityColor;
+ (UIColor * _Nonnull)omg_headingColor;
+ (UIColor * _Nonnull)omg_navBarIconsColor;
+ (UIColor * _Nonnull)omg_warmGreyColor;
+ (UIColor * _Nonnull)omg_ratingDiscountsColor;
+ (UIColor * _Nonnull)omg_bodyContentColor;
+ (UIColor * _Nonnull)omg_bodyContentWithOpacityColor;
+ (UIColor * _Nonnull)omg_cardBorderColor;
+ (UIColor * _Nonnull)omg_bodyBgColor;
+ (UIColor * _Nonnull)omg_whiteColor;
+ (UIColor * _Nonnull)omg_opaceWhieColor;
+ (UIColor * _Nonnull)omg_alertColor;
+ (UIColor * _Nonnull)omg_navBarTitleBlackColor;
+ (UIColor * _Nonnull)omg_labelOpacityColor;
+ (UIColor * _Nonnull)omg_alertNotifierTextColor;
+ (UIColor * _Nonnull)omg_navBarBgColor;
+ (UIColor * _Nonnull)omg_notifierBgColor;
+ (UIColor * _Nonnull)omg_notifierTextColor;
+ (UIColor * _Nonnull)omg_separatorsColor;
+ (UIColor * _Nonnull)omg_disableButtonBgColor;
+ (UIColor * _Nonnull)omg_navHeaderColor;
+ (UIColor * _Nonnull)omg_navHeaderSeparatorColor;
+ (UIColor * _Nonnull)omg_navOrderTrackColor;
+ (UIColor * _Nonnull)omg_orderSuccessColor;
+ (UIColor * _Nonnull)omg_successTitleColor;
+ (UIColor * _Nonnull)omg_cartProgressColor;
+ (UIColor * _Nonnull)omg_verticalSeparatorColor;
+ (UIColor * _Nonnull)omg_tagStrokeColor;
+ (UIColor * _Nonnull)omg_notifierErrorBgColor;
+ (UIColor * _Nonnull)omg_notifierSeparatorColor;
+ (UIColor * _Nonnull)omg_iceBlueColor;
+ (UIColor * _Nonnull)omg_kiwiGreen20Color;
+ (UIColor * _Nonnull)omg_alert20Color;
+ (UIColor * _Nonnull)omg_boogerColor;
+ (UIColor * _Nonnull)omg_cellSelectedColor;
+ (UIColor * _Nonnull)omg_bannedDrugsColor;
+ (UIColor * _Nonnull)omg_errorTitleColor;
+ (UIColor * _Nonnull)omg_errorBgColor;
+ (UIColor * _Nonnull)omg_successBgColor;
+ (UIColor * _Nonnull)omg_inProcessColor;
+ (UIColor * _Nonnull)omg_gray128Color;
+ (UIColor * _Nonnull)omg_darkBlueColor;
+ (UIColor * _Nonnull)omg_marineBlueColor;
+ (UIColor * _Nonnull)omg_chatNotificationBgColor;
+ (UIColor * _Nonnull)omg_chatNotificationTxtColor;
+ (UIColor * _Nonnull)omg_bleachWhiteColor;
+ (UIColor * _Nonnull)omg_mrpTextColor;
+ (UIColor * _Nonnull)omg_trueGreenColor;
+ (UIColor * _Nonnull)omg_turquoiseBlueColor;

// New Colors

/**
 Primary Text Color (#212121)
 R: 33 G: 33 B: 33
 */

+ (UIColor * _Nonnull)omg_primaryText;

/**
 Secondary Text Color (#616161)
 R: 97 G: 97 B: 97
 */

+ (UIColor * _Nonnull )omg_secondaryText;

/**
 Tertiary Text Color (#9E9E9E)
 R: 158 G: 158 B: 158
 */

+ (UIColor * _Nonnull)omg_tertiaryText;

/**
 Divider/Line Color (#E0E0E0)
 R: 224 G: 224 B: 224
 */

+ (UIColor * _Nonnull )omg_dividerLine;

/**
 Primary Color (#194B67)
 R: 25 G: 75 B: 103
 */

+ (UIColor * _Nonnull)omg_primaryColor;

/**
 Background Color (#F1F1F1)
 R: 241 G: 241 B: 241
 */

+ (UIColor * _Nonnull)omg_backgroundColor;

/**
 CTA Text Color (#FFFFFF)
 R: 255 G: 255 B: 255
 */

+ (UIColor * _Nonnull)omg_ctaText;

/**
 CTA Fill Color (#FF6F61)
 R: 255 G: 111 B: 97
 */

+ (UIColor * _Nonnull)omg_ctaFill;

/**
 Delight Text Color (#1AAB2A)
 R: 26 G: 171 B: 42
 */

+ (UIColor * _Nonnull)omg_delightText;

/**
 Error/Alert Text Color (#D50000)
 R: 213 G: 0 B: 0
 */

+ (UIColor * _Nonnull)omg_errorAlertText;

/**
 Casual Alert Text Color (#F5A625)
 R: 245 G: 166 B: 35
 */

+ (UIColor * _Nonnull)omg_casualAlertText;

/**
 Light Casual Alert Text Color (#FFFAF1)
 R: 255 G: 250 B: 241
 */

+ (UIColor * _Nonnull)omg_lightCasualAlertText;

/**
 Light Background Color (#F2F8FC)
 R: 242 G: 248 B: 252
 */

+ (UIColor * _Nonnull)omg_lightBackground;

/**
 Neutral Text Color (#F5A623)
 R: 245 G: 166 B: 35
 */

+ (UIColor * _Nonnull)omg_neutralText;

/**
 Search Bar Background Color (#E6F2F9)
 R: 230 G: 242 B: 249
 */

+ (UIColor * _Nonnull)omg_searchBarBackground;

/**
 Diagnostics Service Tag Background Color (#0B5A13)
 R: 11 G: 90 B: 19
 */

+ (UIColor * _Nonnull)omg_diagnosticsServiceTagBackground;

/**
 Doctor Service Tag Background Color (#FFE3C2)
 R: 255 G: 227 B: 194
 */

+ (UIColor * _Nonnull)omg_doctorServiceTagBackground;

/**
 Doctor Service Tag Text Color (#685037)
 R: 104 G: 80 B: 55
 */

+ (UIColor * _Nonnull)omg_doctorServiceTagText;

/**
 POSS SKU Medicine Background Color (#05668C)
 R: 5 G: 102 B: 140 A: 0.1
 */

+ (UIColor * _Nonnull)omg_medicineNameBackground;

/**
 POSS SKU Medicine Border Color (#979797)
 R: 151 G: 151 B: 151
 */

+ (UIColor * _Nonnull)omg_medicineNameBorder;

/**
 Dcp Banner Background Color (#942459)
 R: 148 G: 36 B: 89
 */

+ (UIColor * _Nonnull)omg_dcpSecondaryColor;

/**
 Primary Text Color (#f2f2f7)
 R: 242 G: 242 B: 247
 */

+ (UIColor * _Nonnull)omg_toolbarColor;

/**
 Step Up Progress Color (#50dda7)
 R: 80 G: 221 B: 166
 */

+ (UIColor * _Nonnull)omg_stepupProgressColor;

/**
 Dark Gradient Color (#C6C6C6)
 R: 198 G: 198 B: 198
 */

+ (UIColor * _Nonnull)omg_darkGradientColor;

/**
 Light Gradient Color (#ededed)
 R: 237 G: 237 B: 237
 */

+ (UIColor * _Nonnull)omg_lightGradientColor;


/**
 Steup Up PromoBanner Default BG Color (#931877)
 R: 147 G: 24 B: 119
 */

+ (UIColor * _Nonnull)omg_steupUpPromoBannerDefaultBGColor;

/**
 Tint Default BG Color (#FFF3E3)
 R: 255 G: 243 B: 227
 */

+ (UIColor * _Nonnull)omg_tintBGColor;

/**
 SearchBar Tint Color
 Light Grey Color
 */

+ (UIColor * _Nonnull)omg_searchBarTintColor;

/**
 Primary Accent Color (#913D36)
 R: 145 G: 61 B: 54
 */

+ (UIColor * _Nonnull)omg_primaryAccentColor;

/**
 Primary Accent Color (#A6A6A6)
 R: 166 G: 166 B: 166
 */

+ (UIColor * _Nonnull)omg_pageControlTintColor;

/**
 Alert Tint Color (Black)
 R: 0 G: 0 B: 0
 */

+ (UIColor * _Nonnull)omg_alertTintColor;

/**
 Border Color
 R: 234 G: 234 B: 234
 */

+ (UIColor * _Nonnull)omg_borderColor;

/**
(#FFF5E8)
*/

+ (UIColor * _Nonnull)omg_navBarTintColor;

/**
(#D0D0D0)
 */

+ (UIColor * _Nonnull)omg_shadowColor;

/**
 Rating Color (#6C4F33)
 R: 108 G: 79 B: 51
 */

+ (UIColor * _Nonnull)omg_ratingColor;

/**
 Rating View Background Color (#fff3e3)
 R: 255 G: 243 B: 227
 */

+ (UIColor * _Nonnull)omg_ratingViewBackgroundColor;

/**
 Promo Banner Background (#F7F7F7)
 R: 249 G:249 B:249
 */

+ (UIColor * _Nonnull)omg_promoBannerBackground;

/**
 Care Plan Text (#8a2422)
 R: 138 G:36 B:34
 */

+ (UIColor * _Nonnull)omg_carePlanText;

/**
 Care Plan Text (#FFC27A)
 R: 255 G:194 B:122
 */

+ (UIColor * _Nonnull)omg_solidBGColor;

/**
 DCP timer widget decription text color (#636363)
 R:99 G:99 B:99
 */

+ (UIColor * _Nonnull)omg_descriptionText;

/**
 Video Connection State (#333333)
 R: 51 G:51 B:51
*/

+ (UIColor * _Nonnull)omg_videoConnectionStateBgColor;

@end
