//
//  UIColor+Palette.m
//
//  Generated by Zeplin on 7/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+Palette.h"

@implementation UIColor (Palette)

  // #0bc5d8
+ (UIColor * _Nonnull)omg_ctaOpacityColor {
  return [UIColor colorWithRed:11.0f / 255.0f green:197.0f / 255.0f blue:216.0f / 255.0f alpha:0.22f];
}

  // #212121
+ (UIColor * _Nonnull)omg_headingColor {
	return [UIColor colorWithWhite:33.0f / 255.0f alpha:0.87f];
}

  // #1AE5E5
+ (UIColor * _Nonnull)omg_navBarIconsColor {
	return [UIColor colorWithRed:26.0f / 255.0f green:229.0f / 255.0f blue:229.0f / 255.0f alpha:1.0f];
}

  // #9E9E9E
+ (UIColor * _Nonnull)omg_warmGreyColor {
	return [UIColor colorWithWhite:158.0f / 255.0f alpha:1.0f];
}

  // #F7B632
+ (UIColor * _Nonnull)omg_ratingDiscountsColor {
	return [UIColor colorWithRed:247.0f / 255.0f green:182.0f / 255.0f blue:50.0f / 255.0f alpha:1.0f];
}

  // #757575
+ (UIColor * _Nonnull)omg_bodyContentColor {
	return [UIColor colorWithWhite:117.0f / 255.0f alpha:1.0f];
}

  // #E9EEF0
+ (UIColor * _Nonnull)omg_cardBorderColor {
	return [UIColor colorWithRed:233.0f / 255.0f green:238.0f / 255.0f blue:240.0f / 255.0f alpha:1.0f];
}

  // #F8F8F8
+ (UIColor * _Nonnull)omg_bodyBgColor {
	return [UIColor colorWithWhite:248.0f / 255.0f alpha:1.0f];
}

  // #FFFFFF
+ (UIColor * _Nonnull)omg_whiteColor {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

  // #FFFFFF
+ (UIColor * _Nonnull)omg_opaceWhieColor {
  return [UIColor colorWithWhite:255.0f / 255.0f alpha:0.8f];
}

  // #D91414
+ (UIColor * _Nonnull)omg_alertColor {
	return [UIColor colorWithRed:217.0f / 255.0f green:20.0f / 255.0f blue:20.0f / 255.0f alpha:1.0f];
}

  // #212121
+ (UIColor * _Nonnull)omg_navBarTitleBlackColor {
	return [UIColor colorWithWhite:33.0f / 255.0f alpha:1.0f];
}

  // #757575
+ (UIColor * _Nonnull)omg_labelOpacityColor {
	return [UIColor colorWithWhite:117.0f / 255.0f alpha:0.54f];
}

  // #757575
+ (UIColor * _Nonnull)omg_bodyContentWithOpacityColor {
  return [UIColor colorWithWhite:117.0f / 255.0f alpha:0.87f];
}

  // #B05555
+ (UIColor * _Nonnull)omg_alertNotifierTextColor {
	return [UIColor colorWithRed:176.0f / 255.0f green:85.0f / 255.0f blue:85.0f / 255.0f alpha:0.87f];
}

  // #042430
+ (UIColor * _Nonnull)omg_navBarBgColor {
	return [UIColor colorWithRed:4.0f / 255.0f green:36.0f / 255.0f blue:48.0f / 255.0f alpha:1.0f];
}

  // #F7BA3E
+ (UIColor * _Nonnull)omg_notifierBgColor {
	return [UIColor colorWithRed:247.0f / 255.0f green:186.0f / 255.0f blue:62.0f / 255.0f alpha:0.2f];
}

  // #997B3D
+ (UIColor * _Nonnull)omg_notifierTextColor {
	return [UIColor colorWithRed:153.0f / 255.0f green:123.0f / 255.0f blue:61.0f / 255.0f alpha:0.87f];
}

  // #EBEBEB
+ (UIColor * _Nonnull)omg_separatorsColor {
	return [UIColor colorWithWhite:235.0f / 255.0f alpha:1.0f];
}

  // #BDBDBD
+ (UIColor * _Nonnull)omg_disableButtonBgColor {
	return [UIColor colorWithWhite:189.0f / 255.0f alpha:1.0f];
}

  // #0C242F
+ (UIColor * _Nonnull)omg_navHeaderColor {
  return [UIColor colorWithRed:12.0f / 255.0f green:36.0f / 255.0f blue:47.0f / 255.0f alpha:1.0f];
}

  // #E5E5E5
+ (UIColor * _Nonnull)omg_navHeaderSeparatorColor {
  return [UIColor colorWithWhite:229.0f / 255.0f alpha:0.15f];
}

  // #9FA7AB
+ (UIColor * _Nonnull)omg_navOrderTrackColor {
  return [UIColor colorWithRed:159.0f / 255.0f green:167.0f / 255.0f blue:171.0f / 255.0f alpha:1.0f];
}

  // #B6D84E
+ (UIColor * _Nonnull)omg_orderSuccessColor {
  return [UIColor colorWithRed:182.0f / 255.0f green:216.0f / 255.0f blue:78.0f / 255.0f alpha:1.0f];
}

  // #1AAB2A
+ (UIColor * _Nonnull)omg_successTitleColor {
  return [UIColor colorWithRed:26.0f / 255.0f green:171.0f / 255.0f blue:42.0f / 255.0f alpha:1.0f];
}

  // #C2CC5C
+ (UIColor * _Nonnull)omg_cartProgressColor {
  return [UIColor colorWithRed:194.0f / 255.0f green:204.0f / 255.0f blue:92.0f / 255.0f alpha:1.0f];
}

  // #031C26
+ (UIColor * _Nonnull)omg_verticalSeparatorColor {
  return [UIColor colorWithRed:3.0f / 255.0f green:28.0f / 255.0f blue:38.0f / 255.0f alpha:0.4f];
}

  // #C7C7C7
+ (UIColor * _Nonnull)omg_tagStrokeColor {
  return [UIColor colorWithWhite:199.0f / 255.0f alpha:1.0f];
}

  // #D91414
+ (UIColor * _Nonnull)omg_notifierErrorBgColor {
  return [UIColor colorWithRed:217.0f / 255.0f green:20.0f / 255.0f blue:20.0f / 255.0f alpha:0.2f];
}

  // #997B3D
+ (UIColor * _Nonnull)omg_notifierSeparatorColor {
  return [UIColor colorWithRed:153.0f / 255.0f green:123.0f / 255.0f blue:61.0f / 255.0f alpha:0.4f];
}

  // #F6FDFF
+ (UIColor * _Nonnull)omg_iceBlueColor {
  return [UIColor colorWithRed:246.0f / 255.0f green:253.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

  // #B5D84E
+ (UIColor * _Nonnull)omg_kiwiGreen20Color {
  return [UIColor colorWithRed:181.0f / 255.0f green:216.0f / 255.0f blue:78.0f / 255.0f alpha:0.2f];
}

  // #D91414
+ (UIColor * _Nonnull)omg_alert20Color {
  return [UIColor colorWithRed:217.0f / 255.0f green:20.0f / 255.0f blue:20.0f / 255.0f alpha:0.2f];
}

  // #A1AB3F
+ (UIColor * _Nonnull)omg_boogerColor {
  return [UIColor colorWithRed:161.0f / 255.0f green:171.0f / 255.0f blue:63.0f / 255.0f alpha:1.0f];
}

  // #ECFBFC
+ (UIColor * _Nonnull)omg_cellSelectedColor {
  return [UIColor colorWithRed:236.0f / 255.0f green:251.0f / 255.0f blue:252.0f / 255.0f alpha:1.0f];
}

  // #EF4747
+ (UIColor * _Nonnull)omg_bannedDrugsColor {
  return [UIColor colorWithRed:239.0f / 255.0f green:71.0f / 255.0f blue:71.0f / 255.0f alpha:1.0f];
}

  // #EF4747
+ (UIColor * _Nonnull)omg_errorTitleColor {
  return [UIColor colorWithRed:239.0f / 255.0f green:71.0f / 255.0f blue:71.0f / 255.0f alpha:1.0f];
}

  // #EF4747
+ (UIColor * _Nonnull)omg_errorBgColor {
  return [UIColor colorWithRed:239.0f / 255.0f green:71.0f / 255.0f blue:71.0f / 255.0f alpha:0.1f];
}

  // #19AB2A
+ (UIColor * _Nonnull)omg_successBgColor {
  return [UIColor colorWithRed:25.0f / 255.0f green:171.0f / 255.0f blue:42.0f / 255.0f alpha:0.1f];
}

  // #F39C12
+ (UIColor * _Nonnull)omg_inProcessColor {
  return [UIColor colorWithRed:243.0f / 255.0f green:156.0f / 255.0f blue:18.0f / 255.0f alpha:1.0f];
}

  // #808080
+ (UIColor * _Nonnull)omg_gray128Color {
  return [UIColor colorWithRed:128.0f / 255.0f green:128.0f / 255.0f blue:128.0f / 255.0f alpha:1.0f];
}

  // #076D96
+ (UIColor * _Nonnull)omg_darkBlueColor {
  return [UIColor colorWithRed:7.0f / 255.0f green:109.0f / 255.0f blue:150.0f / 255.0f alpha:1.0f];
}

  // #024B68
+ (UIColor * _Nonnull)omg_marineBlueColor {
  return [UIColor colorWithRed:2.0f / 255.0f green:75.0f / 255.0f blue:104.0f / 255.0f alpha:1.0f];
}

  // #F7BA3E
+ (UIColor * _Nonnull)omg_chatNotificationBgColor {
    return [UIColor colorWithRed:247.0f / 255.0f green:186.0f / 255.0f blue:62.0f / 255.0f alpha:0.2f];
}

  // #997B3D
+ (UIColor * _Nonnull)omg_chatNotificationTxtColor {
    return [UIColor colorWithRed:153.0f / 255.0f green:123.0f / 255.0f blue:61.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_bleachWhiteColor {
  return [UIColor colorWithRed:254.0f / 255.0f green:242.0f / 255.0f blue:214.0f / 255.0f alpha:1.0f];
}

  // #9B9B9B
+ (UIColor * _Nonnull)omg_mrpTextColor {
  return [UIColor colorWithWhite:155.0f / 255.0f alpha:1.0f];
}

// New Colors

+ (UIColor * _Nonnull)omg_primaryText {
  return [UIColor colorWithRed:33.0f / 255.0f green:33.0f / 255.0f blue:33.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull )omg_secondaryText {
  return [UIColor colorWithRed:97.0f / 255.0f green:97.0f / 255.0f blue:97.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_tertiaryText {
  return [UIColor colorWithRed:158.0f / 255.0f green:158.0f / 255.0f blue:158.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_dividerLine {
  return [UIColor colorWithRed:224.0f / 255.0f green:224.0f / 255.0f blue:224.0f / 255.0f alpha:1.0f];
}
// #0D847E
+ (UIColor * _Nonnull)omg_trueGreenColor {
  return [UIColor colorWithRed:13.0f / 255.0f green:132.0f / 255.0f blue:126.0f / 255.0f alpha:1.0f];
}

// #0BC5D8
+ (UIColor * _Nonnull)omg_turquoiseBlueColor {
  return [UIColor colorWithRed:11.0f / 255.0f green:197.0f / 255.0f blue:216.0f / 255.0f alpha:0.14f];
}

// New Colors

+ (UIColor * _Nonnull)omg_primaryColor {
  return [UIColor colorWithRed:25.0f/255.0f green:75.0f/255.0f blue:103.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_backgroundColor {
  return [UIColor colorWithRed:241.0f/255.0f green:241.0f/255.0f blue:241.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_ctaText {
  return [UIColor whiteColor];
}

+ (UIColor * _Nonnull)omg_ctaFill {
  return [UIColor colorWithRed:255.0f / 255.0f green:111.0f / 255.0f blue:97.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_errorAlertText {
  return [UIColor colorWithRed:213.0f / 255.0f green:0.0f / 255.0f blue:0.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_casualAlertText {
  return [UIColor colorWithRed:245.0f/255.0f green:166.0f/255.0f blue:35.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_lightCasualAlertText {
  return [UIColor colorWithRed:255.0f/255.0f green:250.0f/255.0f blue:241.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_lightBackground {
  return [UIColor colorWithRed:242.0f/255.0f green:248.0f/255.0f blue:252.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_delightText {
  return [UIColor colorWithRed:26.0f / 255.0f green:171.0f / 255.0f blue:42.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_neutralText {
  return [UIColor colorWithRed:245.0f / 255.0f green:166.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_searchBarBackground {
  return [UIColor colorWithRed:230.0f / 255.0f green:242.0f / 255.0f blue:249.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_diagnosticsServiceTagBackground {
  return [UIColor colorWithRed:11.0f / 255.0f green:90.0f / 255.0f blue:19.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_doctorServiceTagBackground {
  return [UIColor colorWithRed:255.0f / 255.0f green:227.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_doctorServiceTagText {
  return [UIColor colorWithRed:104.0f / 255.0f green:80.0f / 255.0f blue:55.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_medicineNameBackground {
  return [UIColor colorWithRed:5.0f / 255.0f green:102.0f / 255.0f blue:140.0f / 255.0f alpha:0.1f];
}

+ (UIColor * _Nonnull)omg_medicineNameBorder {
  return [UIColor colorWithWhite:151.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_dcpSecondaryColor {
  return [UIColor colorWithRed:148.0f / 255.0f green:36.0f / 255.0f blue:89.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_toolbarColor {
  return [UIColor colorWithRed:242.0f / 255.0f green:242.0f / 255.0f blue:247.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_stepupProgressColor {
  return [UIColor colorWithRed:80.0f / 255.0f green:221.0f / 255.0f blue:166.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_darkGradientColor {
  return [UIColor colorWithRed:198.0f / 255.0f green:198.0f / 255.0f blue:198.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_lightGradientColor {
  return [UIColor colorWithRed:237.0f / 255.0f green:237.0f / 255.0f blue:237.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_steupUpPromoBannerDefaultBGColor {
  return [UIColor colorWithRed:147.0f / 255.0f green:24.0f / 255.0f blue:119.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_tintBGColor {
  return [UIColor colorWithRed:255.0f / 255.0f green:243.0f / 255.0f blue:227.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_searchBarTintColor; {
  return [UIColor lightGrayColor];
}

+ (UIColor * _Nonnull)omg_primaryAccentColor {
  return [UIColor colorWithRed:145.0f / 255.0f green:61.0f / 255.0f blue:54.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_pageControlTintColor {
  return [UIColor colorWithRed:166.0f / 255.0f green:166.0f / 255.0f blue:166.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_alertTintColor {
  return [UIColor blackColor];
}

+ (UIColor * _Nonnull)omg_borderColor {
  return [UIColor colorWithWhite:234.0f / 255.0f alpha:1.0f];
}

/**
 (#FFF5E8)
 */

+ (UIColor * _Nonnull)omg_navBarTintColor {
  return [UIColor colorWithRed:255.0f / 255.0f green:245.0f / 255.0f blue:232.0f / 255.0f alpha:1.0f];
}

/**
(#D0D0D0)
 */

+ (UIColor * _Nonnull)omg_shadowColor {
  return [UIColor colorWithRed:208.0f / 255.0f green:208.0f / 255.0f blue:208.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_ratingColor; {
  return [UIColor colorWithRed:108.0f / 255.0f green:79.0f / 255.0f blue:51.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_ratingViewBackgroundColor; {
  return [UIColor colorWithRed:255.0f / 255.0f green:243.0f / 255.0f blue:227.0f / 255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_promoBannerBackground {
  return [UIColor colorWithRed:249.0f/255.0f green:249.0f/255.0f blue:249.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_carePlanText {
  return [UIColor colorWithRed:138.0f/255.0f green:36.0f/255.0f blue:34.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_videoConnectionStateBgColor {
  return [UIColor colorWithRed:51.0f/255.0f green:51.0f/255.0f blue:51.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_solidBGColor {
  return [UIColor colorWithRed:255.0f/255.0f green:194.0f/255.0f blue:122.0f/255.0f alpha:1.0f];
}

+ (UIColor * _Nonnull)omg_descriptionText {
  return [UIColor colorWithRed:99.0f/255.0f green:99.0f/255.0f blue:99.0f/255.0f alpha:1.0f];
}

@end
