//
//  UIFont+Typography.h
//
//  Generated by Zeplin on 7/1/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (Typography)

// H1-H4
+ (UIFont * _Nonnull)omg_h1RegularFont;
+ (UIFont * _Nonnull)omg_h2MediumFont;
+ (UIFont * _Nonnull)omg_h3RegularFont;
+ (UIFont * _Nonnull)omg_h3MediumFont;
+ (UIFont * _Nonnull)omg_h4MediumFont;
+ (UIFont * _Nonnull)omg_h4BoldFont;

// L1-L4
+ (UIFont * _Nonnull)omg_l1RegularPrimaryFont;
+ (UIFont * _Nonnull)omg_l2RegularPrimaryFont;
+ (UIFont * _Nonnull)omg_l2RegularSecondaryFont;
+ (UIFont * _Nonnull)omg_l2MediumPrimaryFont;
+ (UIFont * _Nonnull)omg_l2MediumSecondaryFont;
+ (UIFont * _Nonnull)omg_l3RegularPrimaryFont;
+ (UIFont * _Nonnull)omg_l3RegularSecondaryFont;
+ (UIFont * _Nonnull)omg_l3RegularTertiaryFont;
+ (UIFont * _Nonnull)omg_l3MediumPrimaryFont;
+ (UIFont * _Nonnull)omg_l3MediumSecondaryFont;
+ (UIFont * _Nonnull)omg_l4RegularPrimaryFont;

// Button
+ (UIFont * _Nonnull)omg_btnActiveSmallFont;
+ (UIFont * _Nonnull)omg_btnActiveBigFont;
+ (UIFont * _Nonnull)omg_btnInactiveBigFont;
+ (UIFont * _Nonnull)omg_btnInactiveSmallFont;

// P1-P4
+ (UIFont * _Nonnull)omg_p1RegularFont;
+ (UIFont * _Nonnull)omg_p2RegularFont;
+ (UIFont * _Nonnull)omg_p2MediumFont;
+ (UIFont * _Nonnull)omg_p3RegularFont;
+ (UIFont * _Nonnull)omg_p3MediumFont;
+ (UIFont * _Nonnull)omg_p3RegularErrorFont;
+ (UIFont * _Nonnull)omg_p3BoldFont;
+ (UIFont * _Nonnull)omg_p4RegularFont;
+ (UIFont * _Nonnull)omg_p4RegularNavFont;
+ (UIFont * _Nonnull)omg_p4MediumFont;

// Tab
+ (UIFont * _Nonnull)omg_tabActiveFont;
+ (UIFont * _Nonnull)omg_tabInactiveFont;

// New Font Styles

/**
 Page Title Font (System Font)
 Size: 34 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_pageTitle;

// Heading

/**
 Heading 1 Font (System Font)
 Size: 24 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_headingOne;

/**
 Heading 2 Font (System Font)
 Size: 17 Weight: Semi-Bold
 */

+ (UIFont * _Nonnull)omg_headingTwo;

/**
 Heading 3 Font (System Font)
 Size: 13 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_headingThree;

// SubHeading

/**
 Sub Heading 1 Font (System Font)
 Size: 15 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_subHeadingOne;

/**
 Sub Heading 2 Font (System Font)
 Size: 13 Weight: Semi-Bold
 */

+ (UIFont * _Nonnull)omg_subHeadingTwo;

/**
 Sub Heading 3 Font (System Font)
 Size: 20 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_subHeadingThree;

/**
 Sub Heading 4 Font (System Font)
 Size: 18 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_subHeadingFour;

// BodyOne

/**
 Body 1 Font (System Font)
 Size: 16 Weight: Regular
 */

+ (UIFont * _Nonnull)omg_bodyOne;

/**
 Body 2 Font (System Font)
 Size: 15 Weight: Regular
 */

+ (UIFont * _Nonnull)omg_bodyTwo;

/**
 Body 3 Font (System Font)
 Size: 13 Weight: Medium
 */

+ (UIFont * _Nonnull)omg_bodyThree;

/**
 Body 4 Font (System Font)
 Size: 13 Weight: Regular
 */

+ (UIFont * _Nonnull)omg_bodyFour;

/**
 Body 5 Font (System Font)
 Size: 16 Weight: Medium
 */

+ (UIFont * _Nonnull)omg_bodyFive;
// CTA

/**
 CTA 1 Font (System Font)
 Size: 17 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_ctaOne;

/**
 CTA 2 Font (System Font)
 Size: 15 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_ctaTwo;

/**
 CTA 3 Font (System Font)
 Size: 13 Weight: Bold
 */

+ (UIFont * _Nonnull)omg_ctaThree;

/**
 CTA 4 Font (System Font)
 Size: 12 Weight: Semi-Bold
 */

+ (UIFont * _Nonnull)omg_ctaFour;

// InfoText

/**
 Info Text 1 Font (System Font)
 Size: 12 Weight: Regular
 */

+ (UIFont * _Nonnull)omg_infoTextOne;

/**
 Info Text 2 Font (System Font)
 Size: 10 Weight: Regular
 */

+ (UIFont * _Nonnull)omg_infoTextTwo;

/**
 Info Text 3 Font (System Font)
 Size: 10 Weight: Medium
 */

+ (UIFont * _Nonnull)omg_infoTextThree;

/**
 Picker Text Font (System Font)
 Size: 17 Weight: Medium
 */

+ (UIFont * _Nonnull)omg_pickerText;

// Redeem Free Gift

/**
Free Gift PopUp Heading Font (System Font)
Size: 18 Weight: Bold
*/

+ (UIFont * _Nonnull)omg_freeGiftPopUpHeading;

+ (UIFont * _Nonnull)omg_dcpWidgetSubtitle;

@end
