
default_platform(:ios)
platform :ios do
  desc "Description of what the lane does"
  lane :generate_ipa_develop do
    build_ios_app(
      configuration: "Dev",
      scheme: "Numero",
      clean: true,
      export_method: 'development',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: "fastlane_jenkins.ipa",
    )
  end

desc "Description of what the lane does"
 lane :run_test do
     run_tests(project: "TruthOrDare.xcodeproj", devices: ["iPhone 8"], scheme: "Numero")
 end
 
end